### ISSUE TITLE
argument


### ISSUE THREAD

**Issue by MSWS** [MSWS/DEFYBans#10]
Traceback (most recent call last):
  File "/root/DEFYBans/Bans.py", line 334, in on_message
    lines = await cmd.exec(msg, args)
  File "/root/DEFYBans/Bans.py", line 653, in exec
    info = formatBanInfo(ban)
  File "/root/DEFYBans/Bans.py", line 214, in formatBanInfo
    title = "{} Ban".format(possesive(ban.data["Player"]))
  File "/root/DEFYBans/Bans.py", line 795, in possesive
    return s + "'" if str.lower().endswith("s") else "'s"
TypeError: descriptor 'lower' of 'str' object needs an argument

**Comment by MSWS** [comment]
Fixed by https://github.com/MSWS/DEFYBans/commit/e3a2a6d658eb23542d39ccc877aba14532fa8249
