### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by MSWS** [MSWS/DEFYBans#11]
Traceback (most recent call last):
  File "/root/DEFYBans/Bans.py", line 353, in on_message
    lines = await cmd.exec(msg, args)
  File "/root/DEFYBans/Bans.py", line 659, in exec
    info = formatBanInfo(ban)
  File "/root/DEFYBans/Bans.py", line 223, in formatBanInfo
    color=getDurationColor(ban.data["Banlength"]),
  File "/root/DEFYBans/Bans.py", line 294, in getDurationColor
    if seconds <= Timespan.DAYS.value * 3: return discord.Color.green()
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by MSWS** [comment]
Fixed in 18148aa
