### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '(Expired)'

### ISSUE THREAD

**Issue by MSWS** [MSWS/DEFYBans#16]
Traceback (most recent call last):
  File "/root/DEFYBans/Bans.py", line 359, in on_message
    lines = await cmd.exec(msg, args)
  File "/root/DEFYBans/Bans.py", line 665, in exec
    info = formatBanInfo(ban)
  File "/root/DEFYBans/Bans.py", line 223, in formatBanInfo
    color=getDurationColor(getBanDuration(ban.data["Banlength"])),
  File "/root/DEFYBans/Bans.py", line 285, in getBanDuration
    amo = int(d.split(" ")[0])
ValueError: invalid literal for int() with base 10: '(Expired)'

**Comment by MSWS** [comment]
Duplicate of #12
